app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

index:
    path: /{wildcard}
    controller: AppBundle\Controller\DefaultController::indexAction
    requirements:
        wildcard: .*